package com.wzsport.model;

public class EditQualified {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wzsport_edit_qualified.id
     *
     * @mbg.generated Sun Jan 07 19:21:46 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wzsport_edit_qualified.running_activity_id
     *
     * @mbg.generated Sun Jan 07 19:21:46 CST 2018
     */
    private Long runningActivityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wzsport_edit_qualified.student_id
     *
     * @mbg.generated Sun Jan 07 19:21:46 CST 2018
     */
    private Long studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wzsport_edit_qualified.user_id
     *
     * @mbg.generated Sun Jan 07 19:21:46 CST 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wzsport_edit_qualified.user_name
     *
     * @mbg.generated Sun Jan 07 19:21:46 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wzsport_edit_qualified.is_qualified
     *
     * @mbg.generated Sun Jan 07 19:21:46 CST 2018
     */
    private Boolean isQualified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wzsport_edit_qualified.remarks
     *
     * @mbg.generated Sun Jan 07 19:21:46 CST 2018
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wzsport_edit_qualified.id
     *
     * @return the value of wzsport_edit_qualified.id
     *
     * @mbg.generated Sun Jan 07 19:21:46 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wzsport_edit_qualified.id
     *
     * @param id the value for wzsport_edit_qualified.id
     *
     * @mbg.generated Sun Jan 07 19:21:46 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wzsport_edit_qualified.running_activity_id
     *
     * @return the value of wzsport_edit_qualified.running_activity_id
     *
     * @mbg.generated Sun Jan 07 19:21:46 CST 2018
     */
    public Long getRunningActivityId() {
        return runningActivityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wzsport_edit_qualified.running_activity_id
     *
     * @param runningActivityId the value for wzsport_edit_qualified.running_activity_id
     *
     * @mbg.generated Sun Jan 07 19:21:46 CST 2018
     */
    public void setRunningActivityId(Long runningActivityId) {
        this.runningActivityId = runningActivityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wzsport_edit_qualified.student_id
     *
     * @return the value of wzsport_edit_qualified.student_id
     *
     * @mbg.generated Sun Jan 07 19:21:46 CST 2018
     */
    public Long getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wzsport_edit_qualified.student_id
     *
     * @param studentId the value for wzsport_edit_qualified.student_id
     *
     * @mbg.generated Sun Jan 07 19:21:46 CST 2018
     */
    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wzsport_edit_qualified.user_id
     *
     * @return the value of wzsport_edit_qualified.user_id
     *
     * @mbg.generated Sun Jan 07 19:21:46 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wzsport_edit_qualified.user_id
     *
     * @param userId the value for wzsport_edit_qualified.user_id
     *
     * @mbg.generated Sun Jan 07 19:21:46 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wzsport_edit_qualified.user_name
     *
     * @return the value of wzsport_edit_qualified.user_name
     *
     * @mbg.generated Sun Jan 07 19:21:46 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wzsport_edit_qualified.user_name
     *
     * @param userName the value for wzsport_edit_qualified.user_name
     *
     * @mbg.generated Sun Jan 07 19:21:46 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wzsport_edit_qualified.is_qualified
     *
     * @return the value of wzsport_edit_qualified.is_qualified
     *
     * @mbg.generated Sun Jan 07 19:21:46 CST 2018
     */
    public Boolean getIsQualified() {
        return isQualified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wzsport_edit_qualified.is_qualified
     *
     * @param isQualified the value for wzsport_edit_qualified.is_qualified
     *
     * @mbg.generated Sun Jan 07 19:21:46 CST 2018
     */
    public void setIsQualified(Boolean isQualified) {
        this.isQualified = isQualified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wzsport_edit_qualified.remarks
     *
     * @return the value of wzsport_edit_qualified.remarks
     *
     * @mbg.generated Sun Jan 07 19:21:46 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wzsport_edit_qualified.remarks
     *
     * @param remarks the value for wzsport_edit_qualified.remarks
     *
     * @mbg.generated Sun Jan 07 19:21:46 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
}