package com.wzsport.model;

import java.util.ArrayList;
import java.util.List;

public class RunningActivityDataAnalysisExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table wzsport_running_activity_data_analysis
	 * @mbg.generated  Thu Dec 14 17:05:38 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table wzsport_running_activity_data_analysis
	 * @mbg.generated  Thu Dec 14 17:05:38 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table wzsport_running_activity_data_analysis
	 * @mbg.generated  Thu Dec 14 17:05:38 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_running_activity_data_analysis
	 * @mbg.generated  Thu Dec 14 17:05:38 CST 2017
	 */
	public RunningActivityDataAnalysisExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_running_activity_data_analysis
	 * @mbg.generated  Thu Dec 14 17:05:38 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_running_activity_data_analysis
	 * @mbg.generated  Thu Dec 14 17:05:38 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_running_activity_data_analysis
	 * @mbg.generated  Thu Dec 14 17:05:38 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_running_activity_data_analysis
	 * @mbg.generated  Thu Dec 14 17:05:38 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_running_activity_data_analysis
	 * @mbg.generated  Thu Dec 14 17:05:38 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_running_activity_data_analysis
	 * @mbg.generated  Thu Dec 14 17:05:38 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_running_activity_data_analysis
	 * @mbg.generated  Thu Dec 14 17:05:38 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_running_activity_data_analysis
	 * @mbg.generated  Thu Dec 14 17:05:38 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_running_activity_data_analysis
	 * @mbg.generated  Thu Dec 14 17:05:38 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_running_activity_data_analysis
	 * @mbg.generated  Thu Dec 14 17:05:38 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table wzsport_running_activity_data_analysis
	 * @mbg.generated  Thu Dec 14 17:05:38 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andRunningActivityIdIsNull() {
			addCriterion("running_activity_id is null");
			return (Criteria) this;
		}

		public Criteria andRunningActivityIdIsNotNull() {
			addCriterion("running_activity_id is not null");
			return (Criteria) this;
		}

		public Criteria andRunningActivityIdEqualTo(Long value) {
			addCriterion("running_activity_id =", value, "runningActivityId");
			return (Criteria) this;
		}

		public Criteria andRunningActivityIdNotEqualTo(Long value) {
			addCriterion("running_activity_id <>", value, "runningActivityId");
			return (Criteria) this;
		}

		public Criteria andRunningActivityIdGreaterThan(Long value) {
			addCriterion("running_activity_id >", value, "runningActivityId");
			return (Criteria) this;
		}

		public Criteria andRunningActivityIdGreaterThanOrEqualTo(Long value) {
			addCriterion("running_activity_id >=", value, "runningActivityId");
			return (Criteria) this;
		}

		public Criteria andRunningActivityIdLessThan(Long value) {
			addCriterion("running_activity_id <", value, "runningActivityId");
			return (Criteria) this;
		}

		public Criteria andRunningActivityIdLessThanOrEqualTo(Long value) {
			addCriterion("running_activity_id <=", value, "runningActivityId");
			return (Criteria) this;
		}

		public Criteria andRunningActivityIdIn(List<Long> values) {
			addCriterion("running_activity_id in", values, "runningActivityId");
			return (Criteria) this;
		}

		public Criteria andRunningActivityIdNotIn(List<Long> values) {
			addCriterion("running_activity_id not in", values, "runningActivityId");
			return (Criteria) this;
		}

		public Criteria andRunningActivityIdBetween(Long value1, Long value2) {
			addCriterion("running_activity_id between", value1, value2, "runningActivityId");
			return (Criteria) this;
		}

		public Criteria andRunningActivityIdNotBetween(Long value1, Long value2) {
			addCriterion("running_activity_id not between", value1, value2, "runningActivityId");
			return (Criteria) this;
		}

		public Criteria andCollectionPointAmountIsNull() {
			addCriterion("collection_point_amount is null");
			return (Criteria) this;
		}

		public Criteria andCollectionPointAmountIsNotNull() {
			addCriterion("collection_point_amount is not null");
			return (Criteria) this;
		}

		public Criteria andCollectionPointAmountEqualTo(Integer value) {
			addCriterion("collection_point_amount =", value, "collectionPointAmount");
			return (Criteria) this;
		}

		public Criteria andCollectionPointAmountNotEqualTo(Integer value) {
			addCriterion("collection_point_amount <>", value, "collectionPointAmount");
			return (Criteria) this;
		}

		public Criteria andCollectionPointAmountGreaterThan(Integer value) {
			addCriterion("collection_point_amount >", value, "collectionPointAmount");
			return (Criteria) this;
		}

		public Criteria andCollectionPointAmountGreaterThanOrEqualTo(Integer value) {
			addCriterion("collection_point_amount >=", value, "collectionPointAmount");
			return (Criteria) this;
		}

		public Criteria andCollectionPointAmountLessThan(Integer value) {
			addCriterion("collection_point_amount <", value, "collectionPointAmount");
			return (Criteria) this;
		}

		public Criteria andCollectionPointAmountLessThanOrEqualTo(Integer value) {
			addCriterion("collection_point_amount <=", value, "collectionPointAmount");
			return (Criteria) this;
		}

		public Criteria andCollectionPointAmountIn(List<Integer> values) {
			addCriterion("collection_point_amount in", values, "collectionPointAmount");
			return (Criteria) this;
		}

		public Criteria andCollectionPointAmountNotIn(List<Integer> values) {
			addCriterion("collection_point_amount not in", values, "collectionPointAmount");
			return (Criteria) this;
		}

		public Criteria andCollectionPointAmountBetween(Integer value1, Integer value2) {
			addCriterion("collection_point_amount between", value1, value2, "collectionPointAmount");
			return (Criteria) this;
		}

		public Criteria andCollectionPointAmountNotBetween(Integer value1, Integer value2) {
			addCriterion("collection_point_amount not between", value1, value2, "collectionPointAmount");
			return (Criteria) this;
		}

		public Criteria andConformStepPerSecondAmountIsNull() {
			addCriterion("conform_step_per_second_amount is null");
			return (Criteria) this;
		}

		public Criteria andConformStepPerSecondAmountIsNotNull() {
			addCriterion("conform_step_per_second_amount is not null");
			return (Criteria) this;
		}

		public Criteria andConformStepPerSecondAmountEqualTo(Integer value) {
			addCriterion("conform_step_per_second_amount =", value, "conformStepPerSecondAmount");
			return (Criteria) this;
		}

		public Criteria andConformStepPerSecondAmountNotEqualTo(Integer value) {
			addCriterion("conform_step_per_second_amount <>", value, "conformStepPerSecondAmount");
			return (Criteria) this;
		}

		public Criteria andConformStepPerSecondAmountGreaterThan(Integer value) {
			addCriterion("conform_step_per_second_amount >", value, "conformStepPerSecondAmount");
			return (Criteria) this;
		}

		public Criteria andConformStepPerSecondAmountGreaterThanOrEqualTo(Integer value) {
			addCriterion("conform_step_per_second_amount >=", value, "conformStepPerSecondAmount");
			return (Criteria) this;
		}

		public Criteria andConformStepPerSecondAmountLessThan(Integer value) {
			addCriterion("conform_step_per_second_amount <", value, "conformStepPerSecondAmount");
			return (Criteria) this;
		}

		public Criteria andConformStepPerSecondAmountLessThanOrEqualTo(Integer value) {
			addCriterion("conform_step_per_second_amount <=", value, "conformStepPerSecondAmount");
			return (Criteria) this;
		}

		public Criteria andConformStepPerSecondAmountIn(List<Integer> values) {
			addCriterion("conform_step_per_second_amount in", values, "conformStepPerSecondAmount");
			return (Criteria) this;
		}

		public Criteria andConformStepPerSecondAmountNotIn(List<Integer> values) {
			addCriterion("conform_step_per_second_amount not in", values, "conformStepPerSecondAmount");
			return (Criteria) this;
		}

		public Criteria andConformStepPerSecondAmountBetween(Integer value1, Integer value2) {
			addCriterion("conform_step_per_second_amount between", value1, value2, "conformStepPerSecondAmount");
			return (Criteria) this;
		}

		public Criteria andConformStepPerSecondAmountNotBetween(Integer value1, Integer value2) {
			addCriterion("conform_step_per_second_amount not between", value1, value2, "conformStepPerSecondAmount");
			return (Criteria) this;
		}

		public Criteria andConformDistancePerStepAmountIsNull() {
			addCriterion("conform_distance_per_step_amount is null");
			return (Criteria) this;
		}

		public Criteria andConformDistancePerStepAmountIsNotNull() {
			addCriterion("conform_distance_per_step_amount is not null");
			return (Criteria) this;
		}

		public Criteria andConformDistancePerStepAmountEqualTo(Integer value) {
			addCriterion("conform_distance_per_step_amount =", value, "conformDistancePerStepAmount");
			return (Criteria) this;
		}

		public Criteria andConformDistancePerStepAmountNotEqualTo(Integer value) {
			addCriterion("conform_distance_per_step_amount <>", value, "conformDistancePerStepAmount");
			return (Criteria) this;
		}

		public Criteria andConformDistancePerStepAmountGreaterThan(Integer value) {
			addCriterion("conform_distance_per_step_amount >", value, "conformDistancePerStepAmount");
			return (Criteria) this;
		}

		public Criteria andConformDistancePerStepAmountGreaterThanOrEqualTo(Integer value) {
			addCriterion("conform_distance_per_step_amount >=", value, "conformDistancePerStepAmount");
			return (Criteria) this;
		}

		public Criteria andConformDistancePerStepAmountLessThan(Integer value) {
			addCriterion("conform_distance_per_step_amount <", value, "conformDistancePerStepAmount");
			return (Criteria) this;
		}

		public Criteria andConformDistancePerStepAmountLessThanOrEqualTo(Integer value) {
			addCriterion("conform_distance_per_step_amount <=", value, "conformDistancePerStepAmount");
			return (Criteria) this;
		}

		public Criteria andConformDistancePerStepAmountIn(List<Integer> values) {
			addCriterion("conform_distance_per_step_amount in", values, "conformDistancePerStepAmount");
			return (Criteria) this;
		}

		public Criteria andConformDistancePerStepAmountNotIn(List<Integer> values) {
			addCriterion("conform_distance_per_step_amount not in", values, "conformDistancePerStepAmount");
			return (Criteria) this;
		}

		public Criteria andConformDistancePerStepAmountBetween(Integer value1, Integer value2) {
			addCriterion("conform_distance_per_step_amount between", value1, value2, "conformDistancePerStepAmount");
			return (Criteria) this;
		}

		public Criteria andConformDistancePerStepAmountNotBetween(Integer value1, Integer value2) {
			addCriterion("conform_distance_per_step_amount not between", value1, value2,
					"conformDistancePerStepAmount");
			return (Criteria) this;
		}

		public Criteria andConformSpeedAmountIsNull() {
			addCriterion("conform_speed_amount is null");
			return (Criteria) this;
		}

		public Criteria andConformSpeedAmountIsNotNull() {
			addCriterion("conform_speed_amount is not null");
			return (Criteria) this;
		}

		public Criteria andConformSpeedAmountEqualTo(Integer value) {
			addCriterion("conform_speed_amount =", value, "conformSpeedAmount");
			return (Criteria) this;
		}

		public Criteria andConformSpeedAmountNotEqualTo(Integer value) {
			addCriterion("conform_speed_amount <>", value, "conformSpeedAmount");
			return (Criteria) this;
		}

		public Criteria andConformSpeedAmountGreaterThan(Integer value) {
			addCriterion("conform_speed_amount >", value, "conformSpeedAmount");
			return (Criteria) this;
		}

		public Criteria andConformSpeedAmountGreaterThanOrEqualTo(Integer value) {
			addCriterion("conform_speed_amount >=", value, "conformSpeedAmount");
			return (Criteria) this;
		}

		public Criteria andConformSpeedAmountLessThan(Integer value) {
			addCriterion("conform_speed_amount <", value, "conformSpeedAmount");
			return (Criteria) this;
		}

		public Criteria andConformSpeedAmountLessThanOrEqualTo(Integer value) {
			addCriterion("conform_speed_amount <=", value, "conformSpeedAmount");
			return (Criteria) this;
		}

		public Criteria andConformSpeedAmountIn(List<Integer> values) {
			addCriterion("conform_speed_amount in", values, "conformSpeedAmount");
			return (Criteria) this;
		}

		public Criteria andConformSpeedAmountNotIn(List<Integer> values) {
			addCriterion("conform_speed_amount not in", values, "conformSpeedAmount");
			return (Criteria) this;
		}

		public Criteria andConformSpeedAmountBetween(Integer value1, Integer value2) {
			addCriterion("conform_speed_amount between", value1, value2, "conformSpeedAmount");
			return (Criteria) this;
		}

		public Criteria andConformSpeedAmountNotBetween(Integer value1, Integer value2) {
			addCriterion("conform_speed_amount not between", value1, value2, "conformSpeedAmount");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table wzsport_running_activity_data_analysis
	 * @mbg.generated  Thu Dec 14 17:05:38 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wzsport_running_activity_data_analysis
     *
     * @mbg.generated do_not_delete_during_merge Thu Dec 14 16:09:11 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}