package com.wzsport.model;

public class RunningActivityDataAnalysis {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_running_activity_data_analysis.id
	 * @mbg.generated  Fri Dec 15 20:34:01 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_running_activity_data_analysis.running_activity_id
	 * @mbg.generated  Fri Dec 15 20:34:01 CST 2017
	 */
	private Long runningActivityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_running_activity_data_analysis.sport_data_validate_rule_id
	 * @mbg.generated  Fri Dec 15 20:34:01 CST 2017
	 */
	private Long sportDataValidateRuleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_running_activity_data_analysis.collection_point_amount
	 * @mbg.generated  Fri Dec 15 20:34:01 CST 2017
	 */
	private Integer collectionPointAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_running_activity_data_analysis.conform_step_per_second_amount
	 * @mbg.generated  Fri Dec 15 20:34:01 CST 2017
	 */
	private Integer conformStepPerSecondAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_running_activity_data_analysis.conform_distance_per_step_amount
	 * @mbg.generated  Fri Dec 15 20:34:01 CST 2017
	 */
	private Integer conformDistancePerStepAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_running_activity_data_analysis.conform_speed_amount
	 * @mbg.generated  Fri Dec 15 20:34:01 CST 2017
	 */
	private Integer conformSpeedAmount;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_running_activity_data_analysis.id
	 * @return  the value of wzsport_running_activity_data_analysis.id
	 * @mbg.generated  Fri Dec 15 20:34:01 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_running_activity_data_analysis.id
	 * @param id  the value for wzsport_running_activity_data_analysis.id
	 * @mbg.generated  Fri Dec 15 20:34:01 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_running_activity_data_analysis.running_activity_id
	 * @return  the value of wzsport_running_activity_data_analysis.running_activity_id
	 * @mbg.generated  Fri Dec 15 20:34:01 CST 2017
	 */
	public Long getRunningActivityId() {
		return runningActivityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_running_activity_data_analysis.running_activity_id
	 * @param runningActivityId  the value for wzsport_running_activity_data_analysis.running_activity_id
	 * @mbg.generated  Fri Dec 15 20:34:01 CST 2017
	 */
	public void setRunningActivityId(Long runningActivityId) {
		this.runningActivityId = runningActivityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_running_activity_data_analysis.sport_data_validate_rule_id
	 * @return  the value of wzsport_running_activity_data_analysis.sport_data_validate_rule_id
	 * @mbg.generated  Fri Dec 15 20:34:01 CST 2017
	 */
	public Long getSportDataValidateRuleId() {
		return sportDataValidateRuleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_running_activity_data_analysis.sport_data_validate_rule_id
	 * @param sportDataValidateRuleId  the value for wzsport_running_activity_data_analysis.sport_data_validate_rule_id
	 * @mbg.generated  Fri Dec 15 20:34:01 CST 2017
	 */
	public void setSportDataValidateRuleId(Long sportDataValidateRuleId) {
		this.sportDataValidateRuleId = sportDataValidateRuleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_running_activity_data_analysis.collection_point_amount
	 * @return  the value of wzsport_running_activity_data_analysis.collection_point_amount
	 * @mbg.generated  Fri Dec 15 20:34:01 CST 2017
	 */
	public Integer getCollectionPointAmount() {
		return collectionPointAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_running_activity_data_analysis.collection_point_amount
	 * @param collectionPointAmount  the value for wzsport_running_activity_data_analysis.collection_point_amount
	 * @mbg.generated  Fri Dec 15 20:34:01 CST 2017
	 */
	public void setCollectionPointAmount(Integer collectionPointAmount) {
		this.collectionPointAmount = collectionPointAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_running_activity_data_analysis.conform_step_per_second_amount
	 * @return  the value of wzsport_running_activity_data_analysis.conform_step_per_second_amount
	 * @mbg.generated  Fri Dec 15 20:34:01 CST 2017
	 */
	public Integer getConformStepPerSecondAmount() {
		return conformStepPerSecondAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_running_activity_data_analysis.conform_step_per_second_amount
	 * @param conformStepPerSecondAmount  the value for wzsport_running_activity_data_analysis.conform_step_per_second_amount
	 * @mbg.generated  Fri Dec 15 20:34:01 CST 2017
	 */
	public void setConformStepPerSecondAmount(Integer conformStepPerSecondAmount) {
		this.conformStepPerSecondAmount = conformStepPerSecondAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_running_activity_data_analysis.conform_distance_per_step_amount
	 * @return  the value of wzsport_running_activity_data_analysis.conform_distance_per_step_amount
	 * @mbg.generated  Fri Dec 15 20:34:01 CST 2017
	 */
	public Integer getConformDistancePerStepAmount() {
		return conformDistancePerStepAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_running_activity_data_analysis.conform_distance_per_step_amount
	 * @param conformDistancePerStepAmount  the value for wzsport_running_activity_data_analysis.conform_distance_per_step_amount
	 * @mbg.generated  Fri Dec 15 20:34:01 CST 2017
	 */
	public void setConformDistancePerStepAmount(Integer conformDistancePerStepAmount) {
		this.conformDistancePerStepAmount = conformDistancePerStepAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_running_activity_data_analysis.conform_speed_amount
	 * @return  the value of wzsport_running_activity_data_analysis.conform_speed_amount
	 * @mbg.generated  Fri Dec 15 20:34:01 CST 2017
	 */
	public Integer getConformSpeedAmount() {
		return conformSpeedAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_running_activity_data_analysis.conform_speed_amount
	 * @param conformSpeedAmount  the value for wzsport_running_activity_data_analysis.conform_speed_amount
	 * @mbg.generated  Fri Dec 15 20:34:01 CST 2017
	 */
	public void setConformSpeedAmount(Integer conformSpeedAmount) {
		this.conformSpeedAmount = conformSpeedAmount;
	}
}