package com.wzsport.mapper;

import com.wzsport.model.EditQualified;
import com.wzsport.model.EditQualifiedExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface EditQualifiedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wzsport_edit_qualified
     *
     * @mbg.generated Sun Jan 07 19:21:46 CST 2018
     */
    long countByExample(EditQualifiedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wzsport_edit_qualified
     *
     * @mbg.generated Sun Jan 07 19:21:46 CST 2018
     */
    int deleteByExample(EditQualifiedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wzsport_edit_qualified
     *
     * @mbg.generated Sun Jan 07 19:21:46 CST 2018
     */
    @Delete({
        "delete from wzsport_edit_qualified",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wzsport_edit_qualified
     *
     * @mbg.generated Sun Jan 07 19:21:46 CST 2018
     */
    @Insert({
        "insert into wzsport_edit_qualified (running_activity_id, student_id, ",
        "user_id, user_name, ",
        "is_qualified, remarks)",
        "values (#{runningActivityId,jdbcType=BIGINT}, #{studentId,jdbcType=BIGINT}, ",
        "#{userId,jdbcType=BIGINT}, #{userName,jdbcType=VARCHAR}, ",
        "#{isQualified,jdbcType=BIT}, #{remarks,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(EditQualified record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wzsport_edit_qualified
     *
     * @mbg.generated Sun Jan 07 19:21:46 CST 2018
     */
    int insertSelective(EditQualified record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wzsport_edit_qualified
     *
     * @mbg.generated Sun Jan 07 19:21:46 CST 2018
     */
    List<EditQualified> selectByExample(EditQualifiedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wzsport_edit_qualified
     *
     * @mbg.generated Sun Jan 07 19:21:46 CST 2018
     */
    @Select({
        "select",
        "id, running_activity_id, student_id, user_id, user_name, is_qualified, remarks",
        "from wzsport_edit_qualified",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.wzsport.mapper.EditQualifiedMapper.BaseResultMap")
    EditQualified selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wzsport_edit_qualified
     *
     * @mbg.generated Sun Jan 07 19:21:46 CST 2018
     */
    int updateByExampleSelective(@Param("record") EditQualified record, @Param("example") EditQualifiedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wzsport_edit_qualified
     *
     * @mbg.generated Sun Jan 07 19:21:46 CST 2018
     */
    int updateByExample(@Param("record") EditQualified record, @Param("example") EditQualifiedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wzsport_edit_qualified
     *
     * @mbg.generated Sun Jan 07 19:21:46 CST 2018
     */
    int updateByPrimaryKeySelective(EditQualified record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wzsport_edit_qualified
     *
     * @mbg.generated Sun Jan 07 19:21:46 CST 2018
     */
    @Update({
        "update wzsport_edit_qualified",
        "set running_activity_id = #{runningActivityId,jdbcType=BIGINT},",
          "student_id = #{studentId,jdbcType=BIGINT},",
          "user_id = #{userId,jdbcType=BIGINT},",
          "user_name = #{userName,jdbcType=VARCHAR},",
          "is_qualified = #{isQualified,jdbcType=BIT},",
          "remarks = #{remarks,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(EditQualified record);
}